apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
    app: frontend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parameters
  namespace: ns-dev
  labels:
    env: dev
    app: frontend
data:
  kafka_url: http://svc-kafka:9000
  api_webhook: http://midominio.com/payment
  method_webhook: post
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-dev
  namespace: ns-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      namespace: ns-dev
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: serverweb
          image: nginx:alpine
          env:
            - name: KAFKA_BROKERS_NUMBER
              value: "1"
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: parameters
                  key: kafka_url
            - name: API_WEBHOOK
              valueFrom:
                configMapKeyRef:
                  name: parameters
                  key: api_webhook
            - name: METHOD_WEBHOOK
              valueFrom:
                configMapKeyRef:
                  name: parameters
                  key: method_webhook
