apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-set
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: serverweb
          image: python:3.6-alpine
          command:
            [
              "sh",
              "-c",
              "echo 'pagina creada para que python 3.6 la ejecute' > index.html && python -m http.server 8082",
            ]
