services:
  server-web:
    image: nginx:stable-alpine
    container_name: server-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /app

  php-fpm:
    image: php:8.2.13-fpm-alpine3.18
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
