apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
    app: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-prd
  labels:
    env: prd
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-dev
  namespace: ns-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      namespace: ns-dev
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: serverweb
          image: nginx:alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-prd
  namespace: ns-prd
spec:
  replicas: 5
  selector:
    matchLabels:
      env: prd
      app: frontend
  template:
    metadata:
      namespace: ns-prd
      labels:
        env: prd
        app: frontend
    spec:
      containers:
        - name: serverweb
          image: nginx:alpine
