services:
  server-web:
    image: nginx:stable-alpine
    container_name: server-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    image: php:8.2.13-fpm-alpine3.18
    container_name: php
    volumes:
      - ./src:/var/www/html
