apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
    app: frontend
---
apiVersion: v1
kind: Secret
metadata:
  name: super-secretos
  namespace: ns-dev
  labels:
    env: dev
    app: frontend
data:
  db_host: c3ZjLW15c3Fs
  db_port: MzMwNg==
  db_user: dXNlci1teXNxbA==
  db_pass: MTIzNDU=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-dev
  namespace: ns-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      namespace: ns-dev
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: serverweb
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: super-secretos
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: super-secretos
                  key: db_port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: super-secretos
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: super-secretos
                  key: db_pass
