apiVersion: v1
kind: Pod
metadata:
  name: server-web
  labels:
    env: dev
    app: frontend
spec:
  containers:
    - name: devops
      image: sonarqube:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: quality-code
  labels:
    env: dev
    app: frontend
spec:
  containers:
    - name: devops
      image: sonarqube:alpine
