apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    mysql: ready
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      mysql: ready
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    mysql: ready
spec:
  replicas: 1
  selector:
    matchLabels:
      mysql: ready
  template:
    metadata:
      labels:
        mysql: ready
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345678"
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: vol-mysql
      volumes:
        - name: vol-mysql
          persistentVolumeClaim:
            claimName: test-pvc
