apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-set
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: web
          image: nginx:alpine
          volumeMounts:
            - name: storagenginx
              mountPath: "/usr/share/nginx/html"
  volumeClaimTemplates:
    - metadata:
        name: storagenginx
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
