FROM node:20-alpine as base
ARG DIR
WORKDIR /app

FROM base as build
COPY ${DIR}/package*.json .
RUN npm ci
COPY ${DIR}/ .
RUN npm run build

FROM nginx:alpine as production
COPY --from=build /app/dist/ /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]

