FROM node:20-alpine as base
WORKDIR /app

FROM base as deps 
COPY ./package*.json .
RUN npm ci --omit dev

FROM base as build
COPY ./package*.json .
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine as production
COPY --from=build /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]

