services:
  server-web:
    image: nginx:alpine
    container_name: server-web
    ports:
      - "8080:80"
    volumes:
      - ./www:/app:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    cpus: 0.5
    mem_limit: 128m
